/*

-> dependencies are the external packages that our project needs to run
-> these are usually open source modules that is used to execute certain tasks 
without having to write everything from scratch

eg :
->if we need to built a server in node.js instead of writing everything ourself we can use express package
 // npm install express

-> this installs express and marks it as dependency in our project


NPM init 

-> the npm init command helps you create package.json file 
-> when we run npm init it will generate a package.json file

difference between package.json and package-lock.json

// package.json file

-> this file is heart of the Node.js project it keeps track of
   -> project info (name, version, description, author)
   -> scripts we can run (npm start, npm test)
   -> other dependencies (external packages our project needs)
   -> DevDependencies (for development and it is not used after the coding part completion
   rather it is used in development time not in deploymet time)
   -> lists project metadata and declares dependencies
   -> it can be created by us or npm init
   -> it declares version ranges (eg : ^1.2.0)
    -> we can edit it normally or manually
    -> it is mostly used by developers, ci/cd tools
    -> it should be present in the project



// package-lock.json

   -> records the exact version of every installed package
   -> it is automatically generated by npm when we insatll packages
   -> it displays the exact version insatlled (eg : 1.2.3)
   -> we cant edit it manually
   -> it is used by npm for consistency in installs
   -> it is not required in project, but it is recommended to have







*/